# Generated by Django 6.0.7 on 2026-08-04 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tandj_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='package',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
    ]
