"""
Django settings for tandj project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a91^0g_=24rzvpl01k%=%xqk(o5x14(w#3sxbwk__w0m7dvj5-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'tanduleisurehotel.in',
    'www.tanduleisurehotel.in',
    't-u-mw2v.onrender.com',
    'localhost',
    '127.0.0.1',
    '*'
]




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',

    'django.contrib.staticfiles',
    'django.contrib.sites',      # required by sitemaps framework
    'django.contrib.sitemaps',
     'storages',
    'tandj_app',
]
SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tandj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'tandj_app.context_processors.booking_modal_rooms',
            ],
        },
    },
]

WSGI_APPLICATION = 'tandj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get(
            'DATABASE_URL',
            'postgresql://postgres.bfjfxupkcufrsoegciul:M1l683FrLohaEAjy@aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres'
        ),
        conn_max_age=600,
        ssl_require=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True

# =========================
# STATIC FILES
# =========================

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

import os
os.environ.setdefault("AWS_REQUEST_CHECKSUM_CALCULATION", "when_required")
os.environ.setdefault("AWS_RESPONSE_CHECKSUM_VALIDATION", "when_required")
# =========================
# SUPABASE S3 MEDIA STORAGE
# =========================

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "access_key": os.environ.get("SUPABASE_S3_ACCESS_KEY_ID"),
            "secret_key": os.environ.get("SUPABASE_S3_SECRET_ACCESS_KEY"),

            "bucket_name": os.environ.get(
                "SUPABASE_STORAGE_BUCKET",
                "media"
            ),

            "endpoint_url": os.environ.get(
                "SUPABASE_S3_ENDPOINT",
                "https://iqmgreuelpkcnkxalzwg.storage.supabase.co/storage/v1/s3"
            ),

            "region_name": os.environ.get(
                "SUPABASE_S3_REGION",
                "ap-southeast-1"
            ),

            "signature_version": "s3v4",
            "addressing_style": "path",

            "file_overwrite": True,
            "querystring_auth": False,

            "custom_domain": os.environ.get(
                "SUPABASE_PUBLIC_DOMAIN",
                "iqmgreuelpkcnkxalzwg.supabase.co/storage/v1/object/public/media"
            ),

            "object_parameters": {
                "CacheControl": "max-age=86400",
            },
        },
    },

    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.zoho.in'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'mail@tanduleisurehotel.in'
EMAIL_HOST_PASSWORD = '1srN QpAF 61FJ'
DEFAULT_FROM_EMAIL = 'T & U<mail@tanduleisurehotel.in>'
RECAPTCHA_SITE_KEY = '6Lc9rrMtAAAAACnAgzVEwzYgJHNHhzPN4xB3UWQf'
RECAPTCHA_SECRET_KEY = '6Lc9rrMtAAAAAMp0dZdJcwcwh0RcKbglmyvEU8ra'